### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Codezilla#6]
Add more lines to the description part to describe the project. 
Alternatively, contributor images of this project can be added.

**Comment by akebu6** [comment]
What exactly do you want added?

**Comment by Susmita-Dey** [comment]
Images of contributors and more about the functionality of the project

**Comment by akebu6** [comment]
> Images of contributors and more about the functionality of the project 

I can work on it

**Comment by Susmita-Dey** [comment]
Note that the contributors will be fetched from this github repo.

**Comment by akebu6** [comment]
> Note that the contributors will be fetched from this github repo.

Okay, noted
